permalink: /blog/:categories/:year/:month/:day/:title.html

# Site settings
title: Christopher Lovell
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
#  Technology, Cosmology and other random noise
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://polyphant1.github.io" # the base hostname & protocol for your site
#twitter_username: polyphantastic
github_username:  polyphant1
linkedin_username: lovellchristopher

# Build settings
markdown: kramdown

# Pagination
pagination: 10
paginate_path: "blog/page:num/"

# twitter
author:
    twitter: chrisclovell
    linkedin: lovellchristopher