permalink: /blog/:categories/:year/:month/:day/:title.html

# Site settings
title: Polyphant
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
#  Technology, Cosmology and other random noise
baseurl: "" # the subpath of your site, e.g. /blog/
url: "polyphant.com" # the base hostname & protocol for your site
#twitter_username: polyphantastic
github_username:  polyphant1
linkedin_username: lovellchristopher
stackexchange_username: polyphant

# Build settings
markdown: kramdown

# Pagination
pagination: 5
paginate_path: "/page:num/"

# twitter
author:
    twitter: chrisclovell
    linkedin: lovellchristopher